### ISSUE TITLE
Determine number of tests that are failing at 1024x768

### ISSUE THREAD

**Issue by megahirt** [sil-student-projects/2018-web-languageforge-e2e#28]

**Comment by megahirt** [comment]
On Kris's machine, one test failed when running the entire LF test suite:
E2E Projects List App
for Normal User
should not list projects the user is not a member of

**Comment by kpgbrink** [comment]
On SF there was one failed spec and executed 257/261:
SFChecks project settings page - project manager
question templates tab
✓ can update an existing template
      ✗ can delete a template
        - Failed: unknown error: Element <button class="btn btn-std" data-ng-disabled="selected.length == 0" data-ng-click="removeTemplates()">...</button> is not clickable at point (315, 239). Other element would receive the click: <div style="max-width: 500px; padding-right: 30px" data-ng-hide="notice.details" data-ng-bind-html="notice.message" class="ng-binding ng-scope">...</div>
          (Session info: chrome=63.0.3239.132)
          (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

**Comment by megahirt** [comment]
I can confirm the same failure on my machine 1024x768 SF (1 failure): 
SFChecks project settings page - project manager
question templates tab
✗ can delete a template

**Comment by megahirt** [comment]
800x600 LF failures:

1) View settings page Semantic Domain field is hidden for Manager
  - Failed: unknown error: Element <li class="breadcrumb-item ng-scope" data-ng-repeat="bc in $ctrl.breadcrumbs" data-ng-class="{active: $last}" data-ng-switch="$last">...</li> is not clickable at point (181, 72). Other element would receive the click: <div uib-alert="" ng-if="!notice.cannotClose" data-ng-class="'alert-' + (notice.type || 'warning')" class="animate-repeat ng-scope ng-isolate-scope alert alert-dismissible alert-success" data-close="$ctrl.closeNotice(notice.id)" role="alert">...</div>
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

2) Editor List and Entry Configuration check make "en" input system invisible for "Word" field
  - Failed: unknown error: Element <li class="breadcrumb-item ng-scope" data-ng-repeat="bc in $ctrl.breadcrumbs" data-ng-class="{active: $last}" data-ng-switch="$last">...</li> is not clickable at point (181, 72). Other element would receive the click: <div uib-alert="" ng-if="!notice.cannotClose" data-ng-class="'alert-' + (notice.type || 'warning')" class="animate-repeat ng-scope ng-isolate-scope alert alert-dismissible alert-success" data-close="$ctrl.closeNotice(notice.id)" role="alert">...</div>
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

3) Editor List and Entry Configuration check Word has only "th", "tipa" and "taud" visible
  - Failed: No element found using locator: By(css selector, .dc-entry)

4) Editor List and Entry first entry is selected if entryId unknown
  - Failed: No element found using locator: By(css selector, *[id="lexAppEditView"])

5) Editor List and Entry URL entry id changes with entry
  - Expected '' to match /[0-9a-z_]{6,24}/.
  - Failed: No element found using locator: By(css selector, *[id="lexAppEditView"])

6) Editor List and Entry new word is visible in browse page
  - Failed: No element found using locator: By(css selector, .lexAppToolbar)

7) Editor List and Entry check that word count is still correct in browse page
  - Failed: Wait timed out after 3012ms

8) Editor List and Entry remove new word to restore original word count
  - Failed: Wait timed out after 3013ms

9) Editor List and Entry previous entry is selected after delete
  - Failed: Wait timed out after 3004ms

**Comment by megahirt** [comment]
800x600 SF has (8 failures):

**************************************************
*                    Failures                    *
**************************************************

1) SFChecks project settings page - project manager members tab can remove a member
  - Failed: unknown error: Element <button class="btn btn-std" data-ng-disabled="selected.length == 0" data-ng-show="rights.deleteOther" data-ng-click="removeProjectUsers()">...</button> is not clickable at point (510, 79). Other element would receive the click: <div uib-alert="" ng-if="!notice.cannotClose" data-ng-class="'alert-' + (notice.type || 'warning')" class="animate-repeat ng-scope ng-isolate-scope alert alert-dismissible alert-success" data-close="$ctrl.closeNotice(notice.id)" role="alert">...</div>
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

2) SFChecks project settings page - project manager question templates tab setup: click on tab
  - Failed: unknown error: Element <a ng-click="tabset.selectTab($index)" ng-if="tab.visible()" class="nav-link tab-link ng-binding ng-scope" ng-class="{'active': tab.selected}" href="">...</a> is not clickable at point (233, 81). Other element would receive the click: <div uib-alert="" ng-if="!notice.cannotClose" data-ng-class="'alert-' + (notice.type || 'warning')" class="animate-repeat ng-scope ng-isolate-scope alert alert-dismissible alert-success" data-close="$ctrl.closeNotice(notice.id)" role="alert">...</div>
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

3) SFChecks project settings page - project manager question templates tab can add a template
  - Failed: element not visible
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

4) SFChecks project settings page - project manager question templates tab can update an existing template
  - Failed: No element found using locator: By(link text, sound check)

5) SFChecks project settings page - project manager question templates tab can delete a template
  - Failed: element not visible
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

6) the question page a project manager paratext export of flagged answer setup: back to Text, click settings, click on tab
  - Failed: unknown error: Element <a data-ng-click="$ctrl.unregisterBreadCrumb($index)" data-ng-href="#!/5a5438717f848403f20fed6f" class="ng-binding" href="#!/5a5438717f848403f20fed6f">...</a> is not clickable at point (296, 70). Other element would receive the click: <div class="notices">...</div>
    (Session info: chrome=63.0.3239.132)
    (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

7) the question page a project manager paratext export of flagged answer can prepare export for answers flagged for export without comments
  - Failed: No element found using locator: By(css selector, *[id="exportAnswers"])

8) the question page a project manager paratext export of flagged answer can prepare export for answers flagged for export with comments
  - Failed: No element found using locator: by.model("exportConfig.exportComments")

**Comment by kpgbrink** [comment]
I got he same results in sf on 860X600

**Comment by bkastner** [comment]
Closing because this issue is in the "done" column.  Closing it updates the week1 Milestone.
