### ISSUE TITLE
Make Project Settings Page work with mobile

### ISSUE THREAD

**Issue by kpgbrink** [sil-student-projects/2018-web-languageforge-e2e#36]

**Comment by kpgbrink** [comment]
On SF there was one failed spec and executed 257/261:
SFChecks project settings page - project manager
question templates tab
✓ can update an existing template
✗ can delete a template
- Failed: unknown error: Element ... is not clickable at point (315, 239). Other element would receive the click:

...
Currently working on this part

**Comment by bkastner** [comment]
closing - not going to get done.
